name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  quality-gate:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11", "3.12"]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install -r requirements-dev.txt

      - name: Ruff check
        run: python -m ruff check .

      - name: Ruff format check
        run: python -m ruff format --check .

      - name: Pytest
        run: python -m pytest -q
